#!/bin/sh
# Container entrypoint: on first start, generate a minimal config that enables
# the WebUI, then launch the background service.
set -e

WS="${LLAIA_WORKSPACE:-/data}"
mkdir -p "$WS"

CFG="$WS/config.toml"
if [ ! -f "$CFG" ]; then
  cat > "$CFG" <<EOF
# Auto-generated by docker-entrypoint.sh on first start
[webui]
host = "${WEB_HOST:-0.0.0.0}"
port = ${WEB_PORT:-51217}
EOF
fi

exec llaia serve --config-dir "$WS"
