//! 自动生成 Tail Reminder（P6）：对抗长会话风格/身份漂移。
//!
//! 机制：SOUL/USER 每轮都在 system 头部完整重发，但上下文变长后中段注意力稀释，
//! 模型会模仿自己最近几轮的输出而非头部指令（自我模仿漂移）。解法是把最关键的
//! 行为指令同时放到离生成点最近的尾部。内容由 LLM 从 SOUL+USER 自动提炼（用户
//! 无感），存独立文件 `workspace/reminder.md`，不进 MEMORY（避免被 trim/compact
//! 管线摘要掉）。
//!
//! - 触发：文件缺失，或 SOUL+USER 的 md5 与文件内记录不一致（人格/画像变化才重
//!   生成；MEMORY/skills 不参与 hash，避免 memory_write 频繁触发重生成）
//! - 时机：回合起点异步后台生成，写盘后下一轮生效；失败静默降级（本轮无 reminder）
//! - 上限：prompt 约束 + 写盘前硬截断（~120 token ≈ 480 chars，chars/4 口径）

use anyhow::Result;
use md5::{Digest, Md5};
use std::path::{Path, PathBuf};

/// reminder 硬截断字符数（~120 token，chars/4 启发式）
const REMINDER_CHAR_CAP: usize = 480;

/// reminder 文件名（位于 agent 家目录 workspace/）
const REMINDER_FILE: &str = "reminder.md";

/// 生成 prompt：让模型从 SOUL+USER 提炼最易漂移的行为指令
const DISTILL_PROMPT: &str = "\
Below are the SOUL (persona) and USER (profile) definitions of an AI assistant. \
Distill the MOST drift-prone behavioral directives into a short reminder list: \
tone/style rules, address forms, hard preferences, and any instruction the model \
is likely to violate in long conversations. Output ONLY the reminder text, plain \
lines without markdown headings or lists markup. Maximum 120 tokens.\n\n\
# SOUL\n{soul}\n\n# USER\n{user}";

/// SOUL+USER 联合 md5（提醒重生成的触发依据）
pub fn persona_hash(soul: &str, user: &str) -> String {
    let mut h = Md5::new();
    h.update(soul.as_bytes());
    h.update(b"\x00");
    h.update(user.as_bytes());
    let d = h.finalize();
    d.iter().map(|b| format!("{b:02x}")).collect()
}

fn reminder_path(workspace: &Path) -> PathBuf {
    workspace.join(REMINDER_FILE)
}

/// 读取已落盘的 reminder：(hash, text)。文件缺失/格式不符返回 None。
pub fn load_reminder(workspace: &Path) -> Option<(String, String)> {
    let content = std::fs::read_to_string(reminder_path(workspace)).ok()?;
    let rest = content.strip_prefix("<!-- auto-generated by llaia. DO NOT EDIT. -->")?;
    let line = rest.trim_start().strip_prefix("<!-- hash=")?;
    let (hash, text) = line.split_once("-->")?;
    Some((hash.trim().to_string(), text.trim().to_string()))
}

/// 落盘 reminder（幂等覆盖）
fn store_reminder(workspace: &Path, hash: &str, text: &str) -> Result<()> {
    let capped: String = text.chars().take(REMINDER_CHAR_CAP).collect();
    let content =
        format!("<!-- auto-generated by llaia. DO NOT EDIT. -->\n<!-- hash={hash} -->\n{capped}\n");
    std::fs::write(reminder_path(workspace), content)?;
    Ok(())
}

/// 回合起点检查：SOUL+USER hash 与落盘记录一致则直接返回现有文本；
/// 缺失或不一致则 spawn 后台生成任务（写盘后下一轮生效），本轮返回旧值（可能为 None）。
/// 降级模式（无 provider）由调用方保证不进入本函数。
pub fn refresh_reminder(
    workspace: &Path,
    soul: &str,
    user: &str,
    provider: std::sync::Arc<dyn crate::provider::Provider>,
) -> Option<String> {
    let want = persona_hash(soul, user);
    if let Some((h, text)) = load_reminder(workspace) {
        if h == want {
            return (!text.is_empty()).then_some(text);
        }
    }
    // 后台生成：不阻塞当前回合
    let ws = workspace.to_path_buf();
    tokio::spawn(async move {
        match generate_reminder(&ws, provider.as_ref()).await {
            Ok(text) => {
                if let Err(e) = store_reminder(&ws, &want_hash(&soul_of(&ws), &user_of(&ws)), &text)
                {
                    tracing::warn!(error = %e, "failed to store tail reminder");
                } else {
                    tracing::info!("tail reminder regenerated");
                }
            }
            Err(e) => tracing::warn!(error = %e, "tail reminder generation failed"),
        }
    });
    // 本轮用旧值（若有）
    load_reminder(workspace)
        .map(|(_, t)| t)
        .filter(|t| !t.is_empty())
}

// —— 后台任务辅助：从盘上重新读 SOUL/USER（避免把大字符串 clone 进 spawn） ——

fn soul_of(workspace: &Path) -> String {
    std::fs::read_to_string(workspace.join("SOUL.md")).unwrap_or_default()
}
fn user_of(workspace: &Path) -> String {
    std::fs::read_to_string(workspace.join("USER.md")).unwrap_or_default()
}
fn want_hash(soul: &str, user: &str) -> String {
    persona_hash(soul, user)
}

async fn generate_reminder(
    workspace: &Path,
    provider: &dyn crate::provider::Provider,
) -> Result<String> {
    let soul = soul_of(workspace);
    let user = user_of(workspace);
    if soul.is_empty() && user.is_empty() {
        anyhow::bail!("SOUL and USER both empty; nothing to distill");
    }
    let prompt = DISTILL_PROMPT
        .replace("{soul}", &soul)
        .replace("{user}", &user);
    let messages = vec![crate::provider::ChatMessage::user(prompt)];
    let req = crate::provider::ChatRequest {
        messages: &messages,
        tools: None,
        disable_thinking: true,
    };
    let resp = provider.chat(&req).await?;
    let text = resp.text.unwrap_or_default();
    let trimmed = text.trim();
    if trimmed.is_empty() {
        anyhow::bail!("model returned empty reminder");
    }
    Ok(trimmed.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn persona_hash_is_stable_and_order_sensitive() {
        let a = persona_hash("soul", "user");
        assert_eq!(a, persona_hash("soul", "user"));
        assert_ne!(a, persona_hash("soulu", ""));
        assert_ne!(a, persona_hash("", "souluser"));
    }

    #[test]
    fn store_and_load_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let ws = dir.path();
        assert!(load_reminder(ws).is_none());
        store_reminder(ws, "abc123", "简洁口语化").unwrap();
        let (h, t) = load_reminder(ws).unwrap();
        assert_eq!(h, "abc123");
        assert_eq!(t, "简洁口语化");
    }

    #[test]
    fn store_caps_overlong_text() {
        let dir = tempfile::tempdir().unwrap();
        let ws = dir.path();
        store_reminder(ws, "h", &"x".repeat(10_000)).unwrap();
        let (_, t) = load_reminder(ws).unwrap();
        assert_eq!(t.chars().count(), REMINDER_CHAR_CAP);
    }

    #[test]
    fn load_rejects_malformed_file() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(REMINDER_FILE), "random content").unwrap();
        assert!(load_reminder(dir.path()).is_none());
    }
}
